name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write  # Required for PyPI trusted publishing

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python

      # Publish to PyPI when a release is created
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Install uv
        if: ${{ steps.release.outputs.release_created }}
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        if: ${{ steps.release.outputs.release_created }}
        run: uv python install 3.12

      - name: Build package
        if: ${{ steps.release.outputs.release_created }}
        run: uv build

      - name: Publish to PyPI
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1
        # Uses PyPI trusted publishing (OIDC) - no API token needed
